name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
      GISCUS_DISCUSSION_CATEGORY: ${{ secrets.GISCUS_DISCUSSION_CATEGORY }}
      GISCUS_DISCUSSION_CATEGORY_ID: ${{ secrets.GISCUS_DISCUSSION_CATEGORY_ID }}
      GISCUS_PROJECT_ID: ${{ secrets.GISCUS_PROJECT_ID }}
      GOOGLE_ANALYTICS_TAG_ID: ${{ secrets.GOOGLE_ANALYTICS_TAG_ID }}
      ORGANIZATION_NAME: ${{ secrets.ORGANIZATION_NAME }}
      REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
      SITE_TITLE: ${{ secrets.SITE_TITLE }}
      SITE_URL: ${{ secrets.SITE_URL }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run typecheck
      - run: npm run format:check
      - run: npm run build
